"""
Hallucinated Dependency Detection (Anti-Slopsquatting).

Automatically verifies that every package/library referenced in AI-generated
code actually exists in its claimed registry (PyPI, npm).  Cross-references
suggested dependencies against known-good package lists, checks for
suspicious patterns, and blocks hallucinated names that could be registered
by attackers.

Industry context (2025-2026):
- ~20% of LLM-recommended packages do not exist in any public registry
- 43% of hallucinated names recur predictably across prompts
- Slopsquatting attacks register fake AI-hallucinated package names
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum
from typing import Any

# ---------------------------------------------------------------------------
# Data types
# ---------------------------------------------------------------------------

class VerificationStatus(StrEnum):
    VERIFIED = "verified"          # package confirmed to exist
    HALLUCINATED = "hallucinated"  # package does not exist
    SUSPICIOUS = "suspicious"      # exists but has red flags
    UNKNOWN = "unknown"            # unable to verify
    ALLOWLISTED = "allowlisted"    # in org approved list


class RiskLevel(StrEnum):
    SAFE = "safe"
    LOW = "low"
    MEDIUM = "medium"
    HIGH = "high"
    CRITICAL = "critical"


@dataclass
class DependencyCheck:
    """Result of checking a single dependency."""
    package_name: str
    registry: str  # "pypi" | "npm" | "unknown"
    status: VerificationStatus
    risk_level: RiskLevel
    reasons: list[str] = field(default_factory=list)
    suggested_alternative: str | None = None

    def to_dict(self) -> dict[str, Any]:
        return {
            "package_name": self.package_name,
            "registry": self.registry,
            "status": self.status.value,
            "risk_level": self.risk_level.value,
            "reasons": self.reasons,
            "suggested_alternative": self.suggested_alternative,
        }


@dataclass
class VerificationReport:
    """Aggregate report for all dependencies in a code block."""
    checked_at: str
    total_packages: int = 0
    verified: int = 0
    hallucinated: int = 0
    suspicious: int = 0
    checks: list[DependencyCheck] = field(default_factory=list)
    blocked: bool = False

    def to_dict(self) -> dict[str, Any]:
        return {
            "checked_at": self.checked_at,
            "total_packages": self.total_packages,
            "verified": self.verified,
            "hallucinated": self.hallucinated,
            "suspicious": self.suspicious,
            "blocked": self.blocked,
            "checks": [c.to_dict() for c in self.checks],
        }


# ---------------------------------------------------------------------------
# Known good packages (subset — in production this would be a full registry)
# ---------------------------------------------------------------------------

KNOWN_PYPI_PACKAGES: set[str] = {
    # Standard ecosystem
    "fastapi", "flask", "django", "starlette", "uvicorn", "gunicorn",
    "sqlalchemy", "alembic", "pydantic", "httpx", "requests", "aiohttp",
    "celery", "redis", "psycopg2", "asyncpg", "pytest", "pytest-asyncio",
    "pytest-cov", "ruff", "mypy", "black", "isort", "flake8",
    "numpy", "pandas", "scipy", "scikit-learn", "matplotlib",
    "pillow", "boto3", "botocore", "cryptography", "pyjwt",
    "python-dotenv", "click", "typer", "rich", "jinja2",
    "openai", "anthropic", "google-generativeai", "langchain",
    "tiktoken", "transformers", "torch", "tensorflow",
    "passlib", "python-multipart", "python-jose", "bcrypt",
    "sentry-sdk", "prometheus-client", "opentelemetry-api",
    "websockets", "pyyaml", "toml", "orjson", "ujson",
    "beautifulsoup4", "lxml", "scrapy", "selenium",
}

KNOWN_NPM_PACKAGES: set[str] = {
    "react", "react-dom", "react-router", "react-router-dom",
    "next", "vue", "angular", "svelte", "solid-js",
    "typescript", "vite", "webpack", "esbuild", "rollup",
    "express", "koa", "fastify", "hono",
    "axios", "node-fetch", "got", "supertest",
    "jest", "vitest", "mocha", "chai", "cypress", "playwright",
    "eslint", "prettier", "tailwindcss", "postcss",
    "zustand", "redux", "mobx", "jotai", "recoil",
    "zod", "yup", "joi", "ajv",
    "lodash", "underscore", "ramda", "date-fns", "dayjs", "moment",
    "uuid", "nanoid", "chalk", "commander", "yargs",
    "@types/react", "@types/node", "@testing-library/react",
    "prisma", "drizzle-orm", "typeorm", "knex", "sequelize",
    "socket.io", "ws", "graphql", "apollo-server",
    "dotenv", "cors", "helmet", "jsonwebtoken", "bcryptjs",
    "openai", "@anthropic-ai/sdk",
}

# Known hallucinated package names (commonly generated by LLMs)
KNOWN_HALLUCINATED: set[str] = {
    # Python
    "python-utils-pro", "fastapi-advanced", "ai-code-helper",
    "smart-logger", "auto-api-gen", "pyautoml", "quicktest",
    "dataclass-tools", "async-magic", "py-ai-toolkit",
    "flask-autoroute", "django-ai", "pydantic-extra-utils",
    # npm
    "react-ai-components", "auto-form-validator", "smart-state",
    "ai-utils-js", "quick-api-client", "node-ai-helper",
    "express-auto-route", "react-smart-table", "auto-test-gen",
    "typescript-ai-tools", "vite-ai-plugin",
}

# Suspicious name patterns (typosquatting / slopsquatting indicators)
SUSPICIOUS_PATTERNS: list[tuple[str, str]] = [
    (r"^[a-z]+-ai-[a-z]+$", "AI-keyword package name (common hallucination pattern)"),
    (r"^(auto|smart|quick|fast|easy|super)-", "Generic prefix (common hallucination)"),
    (r"^[a-z]+-helper$", "Helper suffix (common hallucination pattern)"),
    (r"^[a-z]+-utils?-?(pro|plus|extra|advanced)$", "Upgraded utils pattern"),
    (r"^py[a-z]{10,}$", "Unusually long py-prefixed name"),
    (r"[0-9]{3,}", "Excessive numbers in package name"),
]


# ---------------------------------------------------------------------------
# Dependency Verifier
# ---------------------------------------------------------------------------

class DependencyVerifier:
    """
    Verifies that AI-generated dependencies are real and safe.

    Responsibilities:
    - Extract package names from import statements and requirement files
    - Check packages against known registries
    - Detect hallucinated / slopsquatted packages
    - Flag suspicious patterns (typosquatting, new packages)
    - Maintain org-level approved dependency catalog
    """

    def __init__(self) -> None:
        self._approved_packages: set[str] = set()
        self._blocked_packages: set[str] = set(KNOWN_HALLUCINATED)
        self._scan_history: list[VerificationReport] = []

    # -- Configuration ------------------------------------------------------

    def add_approved_package(self, name: str) -> None:
        """Add a package to the organization's approved list."""
        self._approved_packages.add(name.lower().strip())

    def add_blocked_package(self, name: str) -> None:
        """Add a package to the blocked list."""
        self._blocked_packages.add(name.lower().strip())

    # -- Extraction ---------------------------------------------------------

    def extract_python_imports(self, code: str) -> list[str]:
        """Extract package names from Python import statements."""
        packages: set[str] = set()

        # import foo / import foo.bar
        for m in re.finditer(r"^\s*import\s+([\w.]+)", code, re.MULTILINE):
            top_level = m.group(1).split(".")[0]
            packages.add(top_level)

        # from foo import bar / from foo.bar import baz
        for m in re.finditer(r"^\s*from\s+([\w.]+)\s+import", code, re.MULTILINE):
            top_level = m.group(1).split(".")[0]
            packages.add(top_level)

        # Filter out stdlib modules
        return [p for p in sorted(packages) if p not in _PYTHON_STDLIB]

    def extract_npm_packages(self, code: str) -> list[str]:
        """Extract package names from JavaScript/TypeScript imports."""
        packages: set[str] = set()

        # import ... from 'package' / import ... from "package"
        for m in re.finditer(
            r"""(?:import|require)\s*\(?[^'"]*['"]([^'"./][^'"]*)['"]\)?""",
            code,
        ):
            pkg = m.group(1)
            # Handle scoped packages (@scope/name)
            if pkg.startswith("@"):
                parts = pkg.split("/")
                if len(parts) >= 2:
                    packages.add(f"{parts[0]}/{parts[1]}")
            else:
                packages.add(pkg.split("/")[0])

        return sorted(packages)

    def extract_requirements(self, content: str) -> list[str]:
        """Extract package names from requirements.txt format."""
        packages: list[str] = []
        for raw_line in content.strip().splitlines():
            stripped = raw_line.strip()
            if not stripped or stripped.startswith("#") or stripped.startswith("-"):
                continue
            # Remove version specifiers
            name = re.split(r"[>=<!~\[]", stripped)[0].strip()
            if name:
                packages.append(name.lower())
        return packages

    # -- Verification -------------------------------------------------------

    def verify_package(self, name: str, registry: str = "auto") -> DependencyCheck:
        """Verify a single package name."""
        name_lower = name.lower().strip()

        # Check approved list first
        if name_lower in self._approved_packages:
            return DependencyCheck(
                package_name=name,
                registry=registry,
                status=VerificationStatus.ALLOWLISTED,
                risk_level=RiskLevel.SAFE,
                reasons=["Package is in organization's approved list"],
            )

        # Check blocked list
        if name_lower in self._blocked_packages:
            return DependencyCheck(
                package_name=name,
                registry=registry,
                status=VerificationStatus.HALLUCINATED,
                risk_level=RiskLevel.CRITICAL,
                reasons=["Package is in known hallucinated/blocked list"],
            )

        # Determine registry
        if registry == "auto":
            registry = self._guess_registry(name_lower)

        # Check against known packages
        known = self._check_known_registry(name_lower, registry)
        if known is not None:
            return known

        # Check suspicious patterns
        suspicious_reasons = self._check_suspicious_patterns(name_lower)
        if suspicious_reasons:
            return DependencyCheck(
                package_name=name,
                registry=registry,
                status=VerificationStatus.SUSPICIOUS,
                risk_level=RiskLevel.MEDIUM,
                reasons=suspicious_reasons,
                suggested_alternative=self._find_similar_package(name_lower, registry),
            )

        # Unknown — can't verify without network access
        return DependencyCheck(
            package_name=name,
            registry=registry,
            status=VerificationStatus.UNKNOWN,
            risk_level=RiskLevel.LOW,
            reasons=["Package not in local registry cache; manual verification needed"],
        )

    def verify_code(self, code: str, language: str = "python") -> VerificationReport:
        """Verify all dependencies in a code block."""
        if language == "python":
            packages = self.extract_python_imports(code)
            registry = "pypi"
        elif language in ("javascript", "typescript"):
            packages = self.extract_npm_packages(code)
            registry = "npm"
        else:
            packages = []
            registry = "unknown"

        now = datetime.now(UTC).isoformat()
        checks = [self.verify_package(p, registry) for p in packages]

        verified = sum(1 for c in checks if c.status == VerificationStatus.VERIFIED)
        hallucinated = sum(1 for c in checks if c.status == VerificationStatus.HALLUCINATED)
        suspicious = sum(1 for c in checks if c.status == VerificationStatus.SUSPICIOUS)
        blocked = hallucinated > 0

        report = VerificationReport(
            checked_at=now,
            total_packages=len(packages),
            verified=verified,
            hallucinated=hallucinated,
            suspicious=suspicious,
            checks=checks,
            blocked=blocked,
        )
        self._scan_history.append(report)
        return report

    def verify_requirements(self, content: str) -> VerificationReport:
        """Verify a requirements.txt file."""
        packages = self.extract_requirements(content)
        now = datetime.now(UTC).isoformat()
        checks = [self.verify_package(p, "pypi") for p in packages]

        verified = sum(1 for c in checks if c.status == VerificationStatus.VERIFIED)
        hallucinated = sum(1 for c in checks if c.status == VerificationStatus.HALLUCINATED)
        suspicious = sum(1 for c in checks if c.status == VerificationStatus.SUSPICIOUS)

        report = VerificationReport(
            checked_at=now,
            total_packages=len(packages),
            verified=verified,
            hallucinated=hallucinated,
            suspicious=suspicious,
            checks=checks,
            blocked=hallucinated > 0,
        )
        self._scan_history.append(report)
        return report

    # -- Stats --------------------------------------------------------------

    def get_stats(self) -> dict[str, Any]:
        """Return aggregate scan statistics."""
        total_scans = len(self._scan_history)
        total_packages = sum(r.total_packages for r in self._scan_history)
        total_hallucinated = sum(r.hallucinated for r in self._scan_history)
        total_blocked = sum(1 for r in self._scan_history if r.blocked)

        return {
            "total_scans": total_scans,
            "total_packages_checked": total_packages,
            "total_hallucinated": total_hallucinated,
            "total_blocked_reports": total_blocked,
            "approved_packages_count": len(self._approved_packages),
            "blocked_packages_count": len(self._blocked_packages),
        }

    @property
    def scan_history(self) -> list[VerificationReport]:
        return list(self._scan_history)

    # -- Internal -----------------------------------------------------------

    def _guess_registry(self, name: str) -> str:
        if name in KNOWN_PYPI_PACKAGES:
            return "pypi"
        if name in KNOWN_NPM_PACKAGES:
            return "npm"
        if name.startswith("@"):
            return "npm"
        return "pypi"

    def _check_known_registry(
        self, name: str, registry: str
    ) -> DependencyCheck | None:
        known_set = (
            KNOWN_PYPI_PACKAGES if registry == "pypi" else KNOWN_NPM_PACKAGES
        )
        if name in known_set:
            return DependencyCheck(
                package_name=name,
                registry=registry,
                status=VerificationStatus.VERIFIED,
                risk_level=RiskLevel.SAFE,
                reasons=[f"Package found in known {registry} registry"],
            )
        return None

    def _check_suspicious_patterns(self, name: str) -> list[str]:
        reasons: list[str] = []
        for pattern, reason in SUSPICIOUS_PATTERNS:
            if re.match(pattern, name):
                reasons.append(reason)
        return reasons

    def _find_similar_package(self, name: str, registry: str) -> str | None:
        """Find the most similar real package name (simple Levenshtein)."""
        known_set = (
            KNOWN_PYPI_PACKAGES if registry == "pypi" else KNOWN_NPM_PACKAGES
        )
        best: str | None = None
        best_dist = float("inf")

        for known in known_set:
            d = _levenshtein(name, known)
            if d < best_dist and d <= 3:  # max 3 edits
                best_dist = d
                best = known

        return best


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _levenshtein(s1: str, s2: str) -> int:
    """Simple Levenshtein distance (no external deps)."""
    if len(s1) < len(s2):
        return _levenshtein(s2, s1)
    if len(s2) == 0:
        return len(s1)

    prev_row = list(range(len(s2) + 1))
    for i, c1 in enumerate(s1):
        curr_row = [i + 1]
        for j, c2 in enumerate(s2):
            insertions = prev_row[j + 1] + 1
            deletions = curr_row[j] + 1
            substitutions = prev_row[j] + (c1 != c2)
            curr_row.append(min(insertions, deletions, substitutions))
        prev_row = curr_row

    return prev_row[-1]


# Python stdlib modules (3.12+) — for filtering
_PYTHON_STDLIB: set[str] = {
    "abc", "aifc", "argparse", "array", "ast", "asyncio", "atexit",
    "base64", "binascii", "bisect", "builtins", "bz2",
    "calendar", "cgi", "cgitb", "chunk", "cmath", "cmd", "code",
    "codecs", "codeop", "collections", "colorsys", "compileall",
    "concurrent", "configparser", "contextlib", "contextvars", "copy",
    "copyreg", "cProfile", "csv", "ctypes", "curses",
    "dataclasses", "datetime", "dbm", "decimal", "difflib", "dis",
    "distutils", "doctest",
    "email", "encodings", "enum", "errno",
    "faulthandler", "fcntl", "filecmp", "fileinput", "fnmatch",
    "fractions", "ftplib", "functools",
    "gc", "getopt", "getpass", "gettext", "glob", "grp", "gzip",
    "hashlib", "heapq", "hmac", "html", "http",
    "idlelib", "imaplib", "importlib", "inspect", "io", "ipaddress",
    "itertools",
    "json",
    "keyword",
    "lib2to3", "linecache", "locale", "logging", "lzma",
    "mailbox", "mailcap", "marshal", "math", "mimetypes", "mmap",
    "modulefinder", "multiprocessing",
    "netrc", "numbers",
    "operator", "optparse", "os",
    "pathlib", "pdb", "pickle", "pickletools", "pipes", "pkgutil",
    "platform", "plistlib", "poplib", "posixpath", "pprint",
    "profile", "pstats", "pty", "pwd", "py_compile", "pyclbr",
    "pydoc",
    "queue", "quopri",
    "random", "re", "readline", "reprlib", "resource", "rlcompleter",
    "runpy",
    "sched", "secrets", "select", "selectors", "shelve", "shlex",
    "shutil", "signal", "site", "smtplib", "socket", "socketserver",
    "sqlite3", "ssl", "stat", "statistics", "string", "stringprep",
    "struct", "subprocess", "sunau", "symtable", "sys", "sysconfig",
    "syslog",
    "tabnanny", "tarfile", "tempfile", "termios", "test", "textwrap",
    "threading", "time", "timeit", "tkinter", "token", "tokenize",
    "tomllib", "trace", "traceback", "tracemalloc", "tty", "turtle",
    "turtledemo", "types", "typing",
    "unicodedata", "unittest", "urllib", "uuid",
    "venv",
    "warnings", "wave", "weakref", "webbrowser", "winreg", "winsound",
    "wsgiref",
    "xml", "xmlrpc",
    "zipapp", "zipfile", "zipimport", "zlib",
    # Common aliases
    "os.path", "collections.abc", "typing_extensions",
}
