"""Output Consistency Checker — cross-run consistency and determinism scoring.

LLMs are non-deterministic by nature.  For production AI pipelines,
output consistency across identical or near-identical inputs matters for
user trust, testability, and reproducibility.  This module measures
how consistent agent outputs are over multiple runs, detects high-variance
areas, and provides a determinism score.

Based on:
- arXiv:2511.10271 "Quality Assurance of LLM-generated Code" (Nov 2025)
- ScienceDirect "Correctness Assessment of Code Generated by LLMs" (2025)
- CodeScene "Agentic AI Coding: Best Practice Patterns" (2026)
- Propel "Agentic Engineering Code Review Guardrails" (2026)
- OneReach "Best Practices for AI Agent Implementations" (2026)

Key capabilities:
- Record outputs for identical prompts across runs
- Structural similarity scoring (Jaccard on token sets)
- Semantic stability detection (output categories)
- Determinism score: 0 (random) to 1 (perfectly consistent)
- Variance hotspot identification by prompt / agent
- Quality gate: deterministic / acceptable / volatile / unstable
- Batch consistency report across prompt families
"""

from __future__ import annotations

import hashlib
import logging
import uuid
from dataclasses import dataclass, field
from datetime import UTC, datetime
from enum import StrEnum

logger = logging.getLogger(__name__)


# ── Enums ────────────────────────────────────────────────────────────────

class ConsistencyGrade(StrEnum):
    DETERMINISTIC = "deterministic"  # >= 0.95
    ACCEPTABLE = "acceptable"  # >= 0.75
    VOLATILE = "volatile"  # >= 0.50
    UNSTABLE = "unstable"  # < 0.50


class GateDecision(StrEnum):
    PASS = "pass"
    WARN = "warn"
    BLOCK = "block"


# ── Data classes ─────────────────────────────────────────────────────────

@dataclass
class OutputRecord:
    """Single output observation."""

    record_id: str = field(default_factory=lambda: str(uuid.uuid4()))
    prompt_hash: str = ""
    agent: str = ""
    output_text: str = ""
    output_category: str = ""  # e.g., "approval", "rejection", "fix"
    timestamp: datetime = field(default_factory=lambda: datetime.now(UTC))


@dataclass
class ConsistencyConfig:
    """Thresholds for consistency grading."""

    deterministic_threshold: float = 0.95
    acceptable_threshold: float = 0.75
    volatile_threshold: float = 0.50
    min_samples: int = 3  # min runs needed to evaluate


@dataclass
class PairSimilarity:
    """Similarity between two outputs."""

    record_a: str
    record_b: str
    jaccard_similarity: float
    category_match: bool


@dataclass
class ConsistencyScore:
    """Consistency score for a prompt."""

    prompt_hash: str
    agent: str
    sample_count: int
    avg_jaccard: float
    category_agreement_pct: float
    determinism_score: float  # combined 0-1
    grade: ConsistencyGrade
    gate: GateDecision


@dataclass
class VarianceHotspot:
    """A prompt/agent combination with high variance."""

    prompt_hash: str
    agent: str
    determinism_score: float
    sample_count: int
    unique_categories: int


@dataclass
class BatchConsistencyReport:
    """Batch consistency report."""

    scores: list[ConsistencyScore]
    hotspots: list[VarianceHotspot]
    overall_determinism: float
    overall_grade: ConsistencyGrade
    total_prompts: int
    total_records: int


# ── Pure helpers ─────────────────────────────────────────────────────────

def _hash_prompt(prompt: str) -> str:
    """Hash a prompt for grouping identical inputs."""
    return hashlib.sha256(prompt.encode()).hexdigest()[:16]


def _tokenize(text: str) -> set[str]:
    """Simple whitespace tokenizer."""
    return set(text.lower().split())


def _jaccard_similarity(a: set[str], b: set[str]) -> float:
    """Compute Jaccard similarity between two token sets."""
    if not a and not b:
        return 1.0
    if not a or not b:
        return 0.0
    intersection = len(a & b)
    union = len(a | b)
    return intersection / union if union > 0 else 0.0


def _compute_pairwise_jaccard(outputs: list[str]) -> float:
    """Average pairwise Jaccard similarity across all outputs."""
    if len(outputs) < 2:
        return 1.0

    token_sets = [_tokenize(o) for o in outputs]
    total = 0.0
    count = 0
    for i in range(len(token_sets)):
        for j in range(i + 1, len(token_sets)):
            total += _jaccard_similarity(token_sets[i], token_sets[j])
            count += 1

    return total / count if count > 0 else 1.0


def _category_agreement(categories: list[str]) -> float:
    """Percentage of outputs in the majority category."""
    if not categories:
        return 1.0
    from collections import Counter
    counts = Counter(categories)
    most_common_count = counts.most_common(1)[0][1]
    return most_common_count / len(categories)


def _grade_consistency(score: float, config: ConsistencyConfig) -> ConsistencyGrade:
    """Grade a determinism score."""
    if score >= config.deterministic_threshold:
        return ConsistencyGrade.DETERMINISTIC
    if score >= config.acceptable_threshold:
        return ConsistencyGrade.ACCEPTABLE
    if score >= config.volatile_threshold:
        return ConsistencyGrade.VOLATILE
    return ConsistencyGrade.UNSTABLE


def _gate_from_grade(grade: ConsistencyGrade) -> GateDecision:
    """Map grade to gate decision."""
    if grade in {ConsistencyGrade.DETERMINISTIC, ConsistencyGrade.ACCEPTABLE}:
        return GateDecision.PASS
    if grade == ConsistencyGrade.VOLATILE:
        return GateDecision.WARN
    return GateDecision.BLOCK


# ── Main class ───────────────────────────────────────────────────────────

class OutputConsistencyChecker:
    """Checks output consistency across multiple runs."""

    def __init__(self, config: ConsistencyConfig | None = None) -> None:
        self._config = config or ConsistencyConfig()
        self._records: list[OutputRecord] = []

    def record_output(
        self,
        prompt: str,
        agent: str,
        output_text: str,
        output_category: str = "",
    ) -> OutputRecord:
        """Record an output observation."""
        rec = OutputRecord(
            prompt_hash=_hash_prompt(prompt),
            agent=agent,
            output_text=output_text,
            output_category=output_category,
        )
        self._records.append(rec)
        return rec

    def record_output_by_hash(
        self,
        prompt_hash: str,
        agent: str,
        output_text: str,
        output_category: str = "",
    ) -> OutputRecord:
        """Record using a pre-computed prompt hash."""
        rec = OutputRecord(
            prompt_hash=prompt_hash,
            agent=agent,
            output_text=output_text,
            output_category=output_category,
        )
        self._records.append(rec)
        return rec

    def evaluate_prompt(self, prompt_hash: str, agent: str = "") -> ConsistencyScore:
        """Evaluate consistency for a specific prompt."""
        matching = [
            r for r in self._records
            if r.prompt_hash == prompt_hash and (not agent or r.agent == agent)
        ]

        if len(matching) < self._config.min_samples:
            return ConsistencyScore(
                prompt_hash=prompt_hash,
                agent=agent,
                sample_count=len(matching),
                avg_jaccard=1.0,
                category_agreement_pct=100.0,
                determinism_score=1.0,
                grade=ConsistencyGrade.DETERMINISTIC,
                gate=GateDecision.PASS,
            )

        outputs = [r.output_text for r in matching]
        categories = [r.output_category for r in matching if r.output_category]

        avg_jaccard = _compute_pairwise_jaccard(outputs)
        cat_agreement = _category_agreement(categories) if categories else 1.0

        # Combined determinism: 70% structural, 30% categorical
        determinism = 0.7 * avg_jaccard + 0.3 * cat_agreement
        determinism = round(determinism, 4)

        grade = _grade_consistency(determinism, self._config)
        gate = _gate_from_grade(grade)

        agent_val = agent or (matching[0].agent if matching else "")

        return ConsistencyScore(
            prompt_hash=prompt_hash,
            agent=agent_val,
            sample_count=len(matching),
            avg_jaccard=round(avg_jaccard, 4),
            category_agreement_pct=round(cat_agreement * 100, 2),
            determinism_score=determinism,
            grade=grade,
            gate=gate,
        )

    def find_hotspots(self, top_n: int = 5) -> list[VarianceHotspot]:
        """Find prompt/agent combos with highest variance."""
        # Group by (prompt_hash, agent)
        groups: dict[tuple[str, str], list[OutputRecord]] = {}
        for r in self._records:
            key = (r.prompt_hash, r.agent)
            groups.setdefault(key, []).append(r)

        hotspots: list[VarianceHotspot] = []
        for (ph, ag), records in groups.items():
            if len(records) < self._config.min_samples:
                continue
            score = self.evaluate_prompt(ph, ag)
            unique_cats = len({r.output_category for r in records if r.output_category})
            hotspots.append(VarianceHotspot(
                prompt_hash=ph,
                agent=ag,
                determinism_score=score.determinism_score,
                sample_count=len(records),
                unique_categories=unique_cats,
            ))

        hotspots.sort(key=lambda h: h.determinism_score)
        return hotspots[:top_n]

    def batch_evaluate(self) -> BatchConsistencyReport:
        """Evaluate consistency across all recorded prompts."""
        groups: dict[tuple[str, str], list[OutputRecord]] = {}
        for r in self._records:
            key = (r.prompt_hash, r.agent)
            groups.setdefault(key, []).append(r)

        scores = []
        for (ph, ag), _records in groups.items():
            scores.append(self.evaluate_prompt(ph, ag))

        hotspots = self.find_hotspots()

        overall = (
            sum(s.determinism_score for s in scores) / len(scores)
            if scores else 1.0
        )

        overall_grade = _grade_consistency(overall, self._config)

        return BatchConsistencyReport(
            scores=scores,
            hotspots=hotspots,
            overall_determinism=round(overall, 4),
            overall_grade=overall_grade,
            total_prompts=len(groups),
            total_records=len(self._records),
        )
