"""Add card modules

Revision ID: d7e6469afc83
Revises: 001_initial
Create Date: 2026-04-02 17:18:18.595482

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d7e6469afc83"
down_revision: Union[str, None] = "001_initial"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("tickets", sa.Column("business_task", sa.Text(), nullable=True))
    op.add_column("tickets", sa.Column("decomposed_task", sa.Text(), nullable=True))
    op.add_column("tickets", sa.Column("coding_task", sa.Text(), nullable=True))
    op.add_column("tickets", sa.Column("ai_prompt", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("tickets", "ai_prompt")
    op.drop_column("tickets", "coding_task")
    op.drop_column("tickets", "decomposed_task")
    op.drop_column("tickets", "business_task")
    # ### end Alembic commands ###
